Cine/cineSistem/Models/Pelicula.cs
using System;
using System.Collections.Generic;

namespace cineSistem.Models;

public partial class Pelicula
{
    public int IdPeli { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public string? Director { get; set; }

    public string? Gender { get; set; }

    public string? Image { get; set; }

    public virtual ICollection<RankingPelicula> RankingPeliculas { get; set; } = new List<RankingPelicula>();
}

Cine/cineSistem/Controllers/PeliculasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using cineSistem.Models;

namespace cineSistem.Controllers
{
    public class PeliculasController : Controller
    {
        private readonly CineSistemContext _context;

        public PeliculasController(CineSistemContext context)
        {
            _context = context;
        }

        // GET: Peliculas
        public async Task<IActionResult> Index()
        {
              return _context.Peliculas != null ? 
                          View(await _context.Peliculas.ToListAsync()) :
                          Problem("Entity set 'CineSistemContext.Peliculas'  is null.");
        }

        // GET: Peliculas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Peliculas == null)
            {
                return NotFound();
            }

            var pelicula = await _context.Peliculas
                .FirstOrDefaultAsync(m => m.IdPeli == id);
            if (pelicula == null)
            {
                return NotFound();
            }

            return View(pelicula);
        }

        // GET: Peliculas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Peliculas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPel,Nombre,Descripcion,Director,Genero,Imagen")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pelicula);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pelicula);
        }

        // GET: Peliculas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Peliculas == null)
            {
                return NotFound();
            }

            var pelicula = await _context.Peliculas.FindAsync(id);
            if (pelicula == null)
            {
                return NotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPeli,Nombre,Descripcion,Director,Genero,Imagen")] Pelicula pelicula)
        {
            if (id != pelicula.IdPeli)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pelicula);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PeliculaExists(pelicula.IdPeli))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pelicula);
        }

        // GET: Peliculas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Peliculas == null)
            {
                return NotFound();
            }

            var pelicula = await _context.Peliculas
                .FirstOrDefaultAsync(m => m.IdPeli == id);
            if (pelicula == null)
            {
                return NotFound();
            }

            return View(pelicula);
        }

        // POST: Peliculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Peliculas == null)
            {
                return Problem("Entity set 'CineSistemContext.Peliculas'  is null.");
            }
            var pelicula = await _context.Peliculas.FindAsync(id);
            if (pelicula != null)
            {
                _context.Peliculas.Remove(pelicula);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PeliculaExists(int id)
        {
          return (_context.Peliculas?.Any(e => e.IdPeli == id)).GetValueOrDefault();
        }
    }
}

Cine/cineSistem/Controllers/RankingPeliculasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using cineSistem.Models;
using Microsoft.AspNetCore.Authorization;

namespace cineSistem.Controllers
{
    [Authorize]
    public class RankingPeliculasController : Controller
    {
        private readonly CineSistemContext _context;

        public RankingPeliculasController(CineSistemContext context)
        {
            _context = context;
        }

        // GET: RankingPeliculas
        public async Task<IActionResult> Index()
        {
            var cineSistemContext = _context.RankingPeliculas.Include(r => r.IdPelNavigation);
            return View(await cineSistemContext.ToListAsync());
        }
        public IActionResult Grafica()
        {
            var peliculasCalificadas = _context.Peliculas
                .Select(p => new
                {
                    Nombre = p.Name,
                    CalificacionPromedio = p.RankingPeliculas.Average(rp => rp.Ranking)
                })
                .OrderByDescending(p => p.CalificacionPromedio)
                .Take(2) // Obtener las 5 mejores calificadas (ajusta según tus necesidades)
                .ToList();

            // Separar los nombres de las películas y las calificaciones promedio
            var nombresPeliculas = peliculasCalificadas.Select(p => p.Nombre).ToArray();
            var calificacionesPromedio = peliculasCalificadas.Select(p => Math.Round(p.CalificacionPromedio, 2)).ToArray();

            ViewBag.NombresPeliculas = nombresPeliculas;
            ViewBag.CalificacionesPromedio = calificacionesPromedio;

            return View();
        }
        // GET: RankingPeliculas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.RankingPeliculas == null)
            {
                return NotFound();
            }

            var rankingPelicula = await _context.RankingPeliculas
                .Include(r => r.IdPelNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rankingPelicula == null)
            {
                return NotFound();
            }

            return View(rankingPelicula);
        }

        // GET: RankingPeliculas/Create
        public IActionResult Create()
        {
            ViewData["IdPel"] = new SelectList(_context.Peliculas, "IdPel", "IdPel");
            return View();
        }

        // POST: RankingPeliculas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdPel,Ranking")] RankingPelicula rankingPelicula)
        {
            
                _context.Add(rankingPelicula);
                await _context.SaveChangesAsync();


            ViewData["IdPel"] = new SelectList(_context.Peliculas, "IdPel", "IdPel", rankingPelicula.IdPeli);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Calificar(int idPel, int rank, string nombre)
        {
            var nuevoRanking = new RankingPelicula
            {
                IdPeli = idPel,
                Ranking = rank
            };
            _context.Add(nuevoRanking);
            _context.SaveChangesAsync();
            TempData["MensajeExito"] = "El ranking de la pelicula "+nombre+" se ha guardado con exito.";
            return RedirectToAction("Index", "Peliculas");
        }
        // GET: RankingPeliculas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.RankingPeliculas == null)
            {
                return NotFound();
            }

            var rankingPelicula = await _context.RankingPeliculas.FindAsync(id);
            if (rankingPelicula == null)
            {
                return NotFound();
            }
            ViewData["IdPel"] = new SelectList(_context.Peliculas, "IdPel", "IdPel", rankingPelicula.IdPeli);
            return View(rankingPelicula);
        }

        // POST: RankingPeliculas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdPel,Ranking")] RankingPelicula rankingPelicula)
        {
            if (id != rankingPelicula.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rankingPelicula);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RankingPeliculaExists(rankingPelicula.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdPel"] = new SelectList(_context.Peliculas, "IdPel", "IdPel", rankingPelicula.IdPeli);
            return View(rankingPelicula);
        }

        // GET: RankingPeliculas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.RankingPeliculas == null)
            {
                return NotFound();
            }

            var rankingPelicula = await _context.RankingPeliculas
                .Include(r => r.IdPelNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rankingPelicula == null)
            {
                return NotFound();
            }

            return View(rankingPelicula);
        }

        // POST: RankingPeliculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.RankingPeliculas == null)
            {
                return Problem("Entity set 'CineSistemContext.RankingPeliculas'  is null.");
            }
            var rankingPelicula = await _context.RankingPeliculas.FindAsync(id);
            if (rankingPelicula != null)
            {
                _context.RankingPeliculas.Remove(rankingPelicula);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RankingPeliculaExists(int id)
        {
          return (_context.RankingPeliculas?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Cine/cineSistem/Views/Peliculas/Create.cshtml
@model cineSistem.Models.Pelicula

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pelicula</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <input asp-for="Director" class="form-control" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cine/cineSistem/Views/Peliculas/Delete.cshtml
@model cineSistem.Models.Pelicula

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pelicula</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Director)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdPeli" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Cine/cineSistem/Views/Peliculas/Details.cshtml
@model cineSistem.Models.Pelicula

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pelicula</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Director)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdPeli">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Cine/cineSistem/Views/Peliculas/Edit.cshtml
@model cineSistem.Models.Pelicula

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pelicula</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdPeli" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <input asp-for="Director" class="form-control" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cine/cineSistem/Views/Peliculas/Index.cshtml
@model IEnumerable<cineSistem.Models.Pelicula>

@{
    ViewData["Title"] = "Index";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<h1 class="text-center">Cartelera CINE</h1>
@if (TempData.ContainsKey("MensajeExito"))
{
    <div class="alert alert-success mensaje-exito text-center">
        @TempData["MensajeExito"]
    </div>
}
<style>
    ul > li{
        display:inline-block;
    }
</style>

<div class="container">
    <div class="row row-cols-1 row-cols-md-2 g-4">

        @foreach (var item in Model)
        {
            <div class="col-md-4">
                <div class="card h-100">
                    <img src="@Html.DisplayFor(modelItem => item.Image)" class="card-img-top " style="height:200px!important" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h5>
                        <p class="card-text">@Html.DisplayFor(modelItem => item.Description)</p>
                        <p class="card-text"><small class="text-muted">Genero: @Html.DisplayFor(modelItem => item.Gender)</small></p>
                        <p>Calificar:</p>
                        <ul>
                            <li>
                                <a asp-controller="RankingPeliculas" asp-action="Calificar" asp-route-idPel="@item.IdPeli" asp-route-rank="1" asp-route-nombre="@item.Name">
                                    <i class="fa-solid fa-star"></i>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="RankingPeliculas" asp-action="Calificar" asp-route-idPel="@item.IdPeli" asp-route-rank="2" asp-route-nombre="@item.Name">
                                    <i class="fa-solid fa-star"></i>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="RankingPeliculas" asp-action="Calificar" asp-route-idPel="@item.IdPeli" asp-route-rank="3" asp-route-nombre="@item.Name">
                                    <i class="fa-solid fa-star"></i>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="RankingPeliculas" asp-action="Calificar" asp-route-idPel="@item.IdPeli" asp-route-rank="4" asp-route-nombre="@item.Name">
                                    <i class="fa-solid fa-star"></i>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="RankingPeliculas" asp-action="Calificar" asp-route-idPel="@item.IdPeli" asp-route-rank="5" asp-route-nombre="@item.Name">
                                    <i class="fa-solid fa-star"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>

        }
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://kit.fontawesome.com/38595e06c7.js" crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {

        var mensajeExito = $(".mensaje-exito");

        if (mensajeExito.length > 0) {
            setTimeout(function () {
                mensajeExito.fadeOut("slow");
            }, 5000); 
        }
    });
</script>